services:
  app:
    image: python:3.11-slim
    working_dir: /app
    volumes:
      - .:/app
      - ./workspace:/app/workspace
      - ./data/arxiv:/app/data/arxiv
      - ./logs:/app/logs
    environment:
      - LLM_BACKEND=${LLM_BACKEND:-groq}
      - GROQ_API_KEY=${GROQ_API_KEY}
      - GROQ_MODEL=${GROQ_MODEL:-llama-3.3-70b-versatile}
      - OLLAMA_HOST=http://ollama:11434
      - OLLAMA_MODEL=${OLLAMA_MODEL:-llama3.1}
      - ARXIV_STORAGE=/app/data/arxiv
      - WORKSPACE_DIR=/app/workspace
      - LOGS_DIR=/app/logs
    command: bash -lc "pip install -r requirements.txt && streamlit run app/app.py --server.port=8501 --server.address=0.0.0.0"
    ports:
      - "8501:8501"
    depends_on:
      - ollama
  filesystem:
    image: ghcr.io/mark3labs/mcp-filesystem-server:latest
    stdin_open: true
    tty: true
    volumes:
      - ./workspace:/workspace
    command: ["/workspace"]
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
volumes:
  ollama: {}
